import type { Metadata } from "next";
import { Inter, Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import { IoLanguage } from "react-icons/io5";
import { FaChevronDown } from "react-icons/fa";
import { FiSun, FiMoon } from "react-icons/fi";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const notoSansKr = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={notoSansKr.className}>
        <section className="text-[0.95em] desktoplg:text-[1.1em] desktopxl:text-[1.5em]">
          <div className="navbar  absolute left-0 top-0 z-[9999] bg-opacity-10 backdrop-blur-md backdrop-saturate-150 max-w-[99%] border-b-2 border-slate-900/10">
            <div className="flex-none">
              <div className="dropdown">
                <div tabIndex={0} role="button" className="btn btn-ghost btn-circle">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    className="inline-block w-5 h-5 stroke-current"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M4 6h16M4 12h16M4 18h16"
                    ></path>
                  </svg>
                </div>
                <ul
                  tabIndex={0}
                  className="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52"
                >
                  <li>
                    <Link href="/main">Main</Link>
                  </li>
                  <li>
                    <Link href="/use">Canvas</Link>
                  </li>
                </ul>
              </div>
            </div>
            <div className="flex-1 items-center">
              <Link href="/main" className="btn btn-ghost text-xl font-extrabold">
                Xiter
              </Link>
              <div className="badge badge-md tracking-widest bg-base-200">0.0.1</div>
            </div>
            <div className="flex items-center space-x-3 p-2">
              <div className="flex items-center">
                <label className="swap swap-flip text-2xl">
                  <input type="checkbox" />
                  <div className="swap-on">
                    <FiSun />
                  </div>
                  <div className="swap-off">
                    <FiMoon />
                  </div>
                </label>
              </div>
              <div className="dropdown dropdown-bottom dropdown-end">
                <div tabIndex={0} role="button" className="flex items-center">
                  <IoLanguage size={23} />
                  <FaChevronDown size={10} />
                </div>
                <ul
                  tabIndex={0}
                  className="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52"
                >
                  <li>
                    <a>English</a>
                  </li>
                  <li>
                    <a>한국어</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          <article>{children}</article>
        </section>
      </body>
    </html>
  );
}
